#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
cartridge_type="python-2.6"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate
export PYTHON_EGG_CACHE=$OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/lib/python-2.6

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/rugebiker/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/rugebiker/manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/rugebiker/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/rugebiker/manage.py collectstatic --noinput
